---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  annotations:
    kubernetes.io/tls-acme: "true"
  labels:
    app: grafana
spec:
  tls:
  - secretName: grafana-tls
    hosts:
    - grafana.svc.kazoku.co
  rules:
  - host: grafana.svc.kazoku.co
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        imagePullPolicy: Always
        env:
        - name: GF_SERVER_DOMAIN
          value: grafana.svc.kazoku.co
        - name: GF_SERVER_ROOT_URL
          value: https://%(domain)s
        - name: GF_DATABASE_TYPE
          value: postgres
        - name: GF_DATABASE_HOST
          value: postgresql:5432
        - name: GF_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: grafana.db
              key: name
        - name: GF_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: grafana.db
              key: username
        - name: GF_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana.db
              key: password
        - name: GF_DATABASE_SSL_MODE
          value: disable
        - name: GF_SECURITY_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: grafana
              key: secret
        - name: GF_USERS_ALLOW_SIGN_UP
          value: "true"
        - name: GF_USERS_ALLOW_ORG_CREATE
          value: "false"
        - name: GF_USERS_AUTO_ASSIGN_ORG
          value: "true"
        - name: GF_USERS_AUTO_ASSIGN_ORG_ROLE
          value: Admin
        - name: GF_AUTH_DISABLE_LOGIN_FORM
          value: "true"
        - name: GF_AUTH_GITHUB_ENABLED
          value: "true"
        - name: GF_AUTH_GITHUB_ALLOW_SIGN_UP
          value: "true"
        - name: GF_AUTH_GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: grafana.github
              key: client-id
        - name: GF_AUTH_GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: grafana.github
              key: client-secret
        - name: GF_AUTH_GITHUB_SCOPES
          value: "user:email,read:org"
        - name: GF_AUTH_GITHUB_AUTH_URL
          value: https://github.com/login/oauth/authorize
        - name: GF_AUTH_GITHUB_TOKEN_URL
          value: https://github.com/login/oauth/access_token
        - name: GF_AUTH_GITHUB_ALLOWED_ORGANIZATIONS
          value: KazokuCo
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
        - name: GF_SESSION_PROVIDER
          value: memory
        - name: GF_LOG_MODE
          value: console
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
