---
apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: registry
spec:
  selector:
    app: registry
  ports:
  - port: 80
    targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
  labels:
    app: registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2.5
        imagePullPolicy: Always
        env:
        - name: REGISTRY_LOG_LEVEL
          value: debug
        - name: REGISTRY_HTTP_ADDR
          value: 0.0.0.0:5000
        - name: REGISTRY_HTTP_HOST
          value: https://registry.svc.kazoku.co
        - name: REGISTRY_HTTP_SECRET
          valueFrom:
            secretKeyRef:
              name: registry
              key: secret
        - name: REGISTRY_HTTP_DEBUG_ADDR
          value: 0.0.0.0:5001
        - name: REGISTRY_REDIS_ADDR
          value: redis.svc.default.cluster.local:6379
        - name: REGISTRY_STORAGE
          value: swift
        - name: REGISTRY_STORAGE_SWIFT_CONTAINER
          valueFrom:
            secretKeyRef:
              name: registry.swift
              key: container
        - name: REGISTRY_STORAGE_SWIFT_REGION
          valueFrom:
            secretKeyRef:
              name: registry.swift
              key: region
        - name: REGISTRY_STORAGE_SWIFT_AUTHURL
          valueFrom:
            secretKeyRef:
              name: openstack
              key: auth_url
        - name: REGISTRY_STORAGE_SWIFT_TENANTID
          valueFrom:
            secretKeyRef:
              name: openstack
              key: tenant_id
        - name: REGISTRY_STORAGE_SWIFT_USERNAME
          valueFrom:
            secretKeyRef:
              name: openstack
              key: username
        - name: REGISTRY_STORAGE_SWIFT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openstack
              key: password
        - name: REGISTRY_STORAGE_SWIFT_ROOTDIRECTORY
          value: /
        - name: REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR
          value: redis
        livenessProbe:
          httpGet:
            path: /debug/health
            port: 5001
        readinessProbe:
          httpGet:
            path: /debug/health
            port: 5001
