---
- hosts: all
  serial: 1
  tasks:

  - name: update packages
    apt: update_cache=yes upgrade=dist

  - name: check if a reboot is needed
    shell: "[ -f /var/run/reboot-required ]"
    failed_when: no
    register: reboot_required
    changed_when: reboot_required.rc == 0

  - name: reboot if needed
    shell: sleep 2 && shutdown -r now
    async: 1
    poll: 0
    when: reboot_required|changed

  - name: wait for host to come back
    local_action: wait_for host={{ ansible_default_ipv4.address }} port=22 delay=5 timeout=180
