---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
  - port: 5432
---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgresql
subsets:
- addresses:
  - ip: 192.168.0.9
  ports:
  - port: 5432
