apiVersion: v1
kind: ConfigMap
metadata:
  name: kakera
  labels:
    app: kakera
data:
  kakera.inc.conf: |-
    # Try to resolve real files in the www directory first, fall back to kakera
    location / {
      try_files $uri $uri/ @kakera;
      error_page 403 = @kakera;
    }

    # Bypass kakera for media and static files
    location /static {
      expires 365d;
    }
    location /media {
      expires 365d;
    }

    # Internal location for kakera
    location @kakera {
      proxy_pass http://kakera;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_redirect off;
    }
  nginx.conf: |-
    worker_processes auto;
    daemon off;
    error_log stderr info;

    events {
      worker_connections 65535;
      multi_accept on;
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      sendfile           on;
      tcp_nopush         on;
      keepalive_timeout  65;

      client_max_body_size 64M;

      set_real_ip_from 0.0.0.0/0;

      upstream kakera {
        # Call the local instance, with no failure timeouts.
        server 127.0.0.1:8000 fail_timeout=0;
      }

      server {
        listen       80 default_server;
        server_name  kazamatsuri.org new.kazamatsuri.org;
        root         /srv/www;

        include kakera.inc.conf;

        # Rewrite old WordPress URLs to their kakera equivalents
        rewrite "^/[0-9]{4}/[0-9]{2}/[0-9]{2}/(.*)$" "/$1" permanent;

        # The real Podcast XML file is on Github Pages for easier publishing
        location = /podcast.xml { return 302 http://podcast.kazamatsuri.org/feed.xml; }
        # Podcast MP3s are now on S3
        location ~ ^/podcast/?(.*)$ { return 302 https://kazamatsuri.s3.amazonaws.com/podcast/$1; }

        # Redirects to the forum (thanks Youtube)
        location ~ ^/go/t/(.*)$ { return 302 https://forum.kazamatsuri.org/t/$1; }
      }

      server {
        listen       80;
        server_name  rokkenjima.org new.rokkenjima.org;
        root         /srv/www;

        include kakera.inc.conf;

        # Redirects to the forum (thanks Youtube)
        location ~ ^/go/t/(.*)$ { return 302 https://forum.rokkenjima.org/t/$1; }
      }
    }
