kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: classic
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/cinder
parameters:
  type: classic
  availability: nova
