---
- name: allow http through firewall
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: allow https through firewall
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: join k8s cluster
  shell: kubeadm reset && kubeadm join --token {{ k8s_token }} {{ k8s_master }}:6443
  async: 60
  poll: 5
  args:
    creates: /etc/kubernetes/kubelet.conf
