---
- name: ensure apt-transport-https is available
  apt: name=apt-transport-https state=present

- name: ensure base packages are available
  apt: name={{ item }} state=present
  with_items:
  - htop
  - vim
  - tmux
  - git
