---
- name: ensure the docker signing key is available
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: ensure the docker repository is present
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: ensure docker is installed
  apt:
    name: docker-ce
    state: present
