apiVersion: v1
kind: Service
metadata:
  name: discourse
  labels:
    app: discourse
spec:
  selector:
    app: discourse
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: discourse
  labels:
    app: discourse
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: discourse
    spec:
      nodeSelector:
        kind: cpu
      containers:
      - name: discourse
        image: registry.default.svc.cluster.local/local_discourse/web:v1.9.0.beta5
        imagePullPolicy: Always
        command:
        - bash
        - -c
        - |
          set -e

          # Just... stuff backups into the upload container. I hate storage servers, so much.
          rmdir /shared/backups
          mkdir -p /shared/uploads/_backups
          ln -s /shared/uploads/_backups /shared/backups

          # Discourse doesn't run as root, but that's what external mounts are mounted as.
          # Technically only needed for the first upload or backup for each forum.
          chown discourse:www-data /shared/{uploads,uploads/_backups,backups}

          # Function to wait for a log file to be created, then tail it.
          function track_log {
            until [[ -f $1 ]]; do sleep 1; done
            tail -f $1
          }

          # Track all log files into 'kubectl logs', then boot up Discourse.
          track_log /shared/log/rails/production.log &
          track_log /shared/log/rails/unicorn.stdout.log &
          track_log /shared/log/rails/unicorn.stderr.log &
          /sbin/boot
          ls -lR /shared/log
        env:
        - name: RAILS_ENV
          value: production
        - name: UNICORN_WORKERS
          value: "2"
        - name: UNICORN_SIDEKIQS
          value: "1"
        - name: RUBY_GLOBAL_METHOD_CACHE_SIZE
          value: "131072"
        - name: RUBY_GC_HEAP_GROWTH_MAX_SLOTS
          value: "40000"
        - name: RUBY_GC_HEAP_INIT_SLOTS
          value: "400000"
        - name: RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR
          value: "1.5"
        - name: DISCOURSE_DEVELOPER_EMAILS
          value: emily@kazoku.co,uppfinnarn@gmail.com
        - name: DISCOURSE_HOSTNAME
          value: forum.kazamatsuri.org
        - name: DISCOURSE_BACKUP_HOSTNAME
          value: forum.test.kazamatsuri.org
        - name: DISCOURSE_DB_HOST
          value: postgresql.default.svc.cluster.local
        - name: DISCOURSE_DB_NAME
          valueFrom:
            secretKeyRef:
              name: discourse.kazamatsuri
              key: db.name
        - name: DISCOURSE_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: discourse.kazamatsuri
              key: db.username
        - name: DISCOURSE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: discourse.kazamatsuri
              key: db.password
        - name: DISCOURSE_DB_POOL
          value: "50"
        - name: DISCOURSE_DB_TIMEOUT
          value: "5000"
        - name: DISCOURSE_REDIS_HOST
          value: redis.default.svc.cluster.local
        - name: DISCOURSE_REDIS_PORT
          value: "6379"
        - name: DISCOURSE_REDIS_DB
          valueFrom:
            secretKeyRef:
              name: discourse.kazamatsuri
              key: redis.db
        - name: DISCOURSE_SMTP_ADDRESS
          valueFrom:
            secretKeyRef:
              name: smtp
              key: host
        - name: DISCOURSE_SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: smtp
              key: port
        - name: DISCOURSE_SMTP_USER_NAME
          valueFrom:
            secretKeyRef:
              name: smtp
              key: username
        - name: DISCOURSE_SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smtp
              key: password
        - name: DISCOURSE_ROKKENJIMA_DB_NAME
          valueFrom:
            secretKeyRef:
              name: discourse.rokkenjima
              key: db.name
        - name: DISCOURSE_ROKKENJIMA_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: discourse.rokkenjima
              key: db.username
        - name: DISCOURSE_ROKKENJIMA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: discourse.rokkenjima
              key: db.password
        - name: DISCOURSE_ROKKENJIMA_REDIS_DB
          valueFrom:
            secretKeyRef:
              name: discourse.rokkenjima
              key: redis.db
        resources:
          requests:
            cpu: 300m
            memory: 3Gi
        ports:
        - name: http
          containerPort: 80
        # two discourse containers absolutely must not run on the same host
        - name: no-colocate
          containerPort: 6969
          hostPort: 6969
        readinessProbe:
          httpGet:
            path: /
            port: http
            httpHeaders:
            - name: Host
              value: forum.kazamatsuri.org
          timeoutSeconds: 10
          periodSeconds: 10
          successThreshold: 4
        volumeMounts:
        - name: nginx-log
          mountPath: /var/log/nginx
        - name: discourse-log
          mountPath: /shared/log
        - name: discourse-uploads
          mountPath: /shared/uploads
        # - name: discourse-backups
        #   mountPath: /shared/backups
      # - name: filebeat
      #   image: docker.elastic.co/beats/filebeat:5.5.0
      #   imagePullPolicy: Always
      #   command:
      #   - sh
      #   - -exc
      #   - |
      #     cat <<EOF > /tmp/filebeat.yml
      #     filebeat.prospectors:
      #     - input_type: log
      #       multiline.pattern: '^([[:space:]]|\z)'
      #       multiline.negate: false
      #       multiline.match: after
      #       paths:
      #       - /shared/log/rails/unicorn.stderr.log
      #       - /shared/log/rails/unicorn.stdout.log
      #     output.logstash:
      #       hosts: ["logstash.default.svc.cluster.local:5044"]
      #     EOF
      #     filebeat -e -v -c /tmp/filebeat.yml
      #   volumeMounts:
      #   - name: nginx-log
      #     mountPath: /var/log/nginx
      #   - name: discourse-log
      #     mountPath: /shared/log
      volumes:
      - name: nginx-log
        emptyDir: {}
      - name: discourse-log
        emptyDir: {}
      - name: discourse-uploads
        cephfs:
          monitors:
          - rook-ceph-mon0.kube-system.svc.cluster.local:6790
          - rook-ceph-mon1.kube-system.svc.cluster.local:6790
          - rook-ceph-mon2.kube-system.svc.cluster.local:6790
          user: admin
          secretRef:
            name: rook-admin
      # - name: discourse-uploads
      #   flexVolume:
      #     driver: kazokuco/svfs
      #     fsType: svfs
      #     options:
      #       container: discourse-uploads
      # - name: discourse-backups
      #   flexVolume:
      #     driver: kazokuco/svfs
      #     fsType: svfs
      #     options:
      #       container: discourse-backups
